# Generated by Django 4.1 on 2023-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cooking_time_ingredientamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Единица измерения'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement_unit'),
        ),
    ]
